name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poppler
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: |
          uv sync --all-extras --dev
          uv pip install -e .

      - name: Run tests
        run: uv run pytest tests
